global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:

  # monitor itself (Prometheus actual server)
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      # `prometheus` - network name (from Docker compose), `localhost` - for local
      - targets: [ 'prometheus:9090' ]

  # monitor API Gateway (Acai)
  - job_name: 'acai_gateway'
    static_configs:
      - targets: ['acai:4000']

  # monitor Auth Service (Durian)
  - job_name: 'durian_auth'
    static_configs:
      - targets: [ 'durian:5000' ]

  # monitor Persist Service (Kiwi)
  - job_name: 'kiwi_persist'
    static_configs:
      - targets: [ 'kiwi:6000' ]