version: "3"

services:
  
  # Client Application
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - acai

  # Acai (Gateway)
  acai:
    container_name: acai
    build:
      context: ./acai
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      PORT: 4000
      MIX_ENV: prod

  # Julik (Service Discovery)
  julik:
    container_name: julik
    build:
      context: ./julik
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      PORT: 8000
      MIX_ENV: prod
    depends_on:
      - acai

  # Durian (Auth Service)
  durian:
    container_name: durian
    build:
      context: ./durian
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
      MIX_ENV: prod
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: durian_prod
      PGHOST: durian_postgres
      PGPORT: 5432
    depends_on:
      - durian_postgres
      - julik

  # Nodex (Generator Service)
  nodex:
    container_name: nodex
    build:
      context: ./nodex
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    depends_on:
      - julik
      - durian

  # Durian Postgres DB (for Auth Service)
  durian_postgres:
    container_name: durian_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
#    volumes:
#      - ./docker-volumes/postgres-data:/var/lib/postgresql/data

#   Kiwi (Persist Service)
  kiwi:
    container_name: kiwi
    build:
      context: ./kiwi
      dockerfile: Dockerfile
    ports:
      - '6000:6000'
    environment:
      PORT: 6000
      MIX_ENV: prod
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: kiwi_prod
      PGHOST: kiwi_postgres
      PGPORT: 5432
    depends_on:
      - kiwi_postgres

  # Kiwi Postgres DB (for Persist Service)
  kiwi_postgres:
    container_name: kiwi_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
#    volumes:
#      - ./docker-volumes/postgres-data:/var/lib/postgresql/data
